name: disposur
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  splashscreen: 
  firebase_auth: ^0.15.4
  cloud_firestore: ^0.13.2
  image_picker: ^0.6.1
  firebase_storage: ^3.0.3
  intl: ^0.16.1
  shared_preferences: ^0.5.7
  printing: ^3.7.0
  path_provider: ^1.6.27
  flutter_full_pdf_viewer: ^1.0.6

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/logo/logo.png